# Generates panorama/layout/custom_game/surftimer_hud.xml - the layout is regular (grids of labels,
# rows of fields, menu rows), so it's generated instead of edited by hand.
# Usage (from the repo root):  ./tools/generate_layout.ps1
# Ids and sizes must match the SurfTimer plugin's src/ST-Player/CustomHud.cs.
param([string]$Out = (Join-Path $PSScriptRoot "..\panorama\layout\custom_game\surftimer_hud.xml"))

$sb = [System.Text.StringBuilder]::new()
function L([string]$s) { [void]$sb.AppendLine($s) }
function Seg([string]$indent, [string]$id, [string]$cls) {
	L "$indent<Label id=`"$id`" class=`"$cls`" hittest=`"false`" text=`"{s:$id}`" />"
}
function GridSlot([string]$slot, [string]$slotClass, [int]$rows, [int]$segs) {
	L "`t`t<Panel id=`"st_$slot`" class=`"Slot $slotClass hidden`" hittest=`"false`">"
	for ($r = 0; $r -lt $rows; $r++) {
		L "`t`t`t<Panel id=`"st_${slot}_$r`" class=`"Row hidden`" hittest=`"false`">"
		for ($s = 0; $s -lt $segs; $s++) { Seg "`t`t`t`t" "st_${slot}_${r}_$s" "Seg hidden" }
		L "`t`t`t</Panel>"
	}
	L "`t`t</Panel>"
	L ""
}

# Popup menu sizes - must match CustomHud.MenuTabCount / MenuItemCount
$MenuTabs = 6
$MenuItems = 8

L '<root>'
L "`t<styles>"
L "`t`t<include src=`"file://{resources}/styles/custom_game/surftimer_hud.css`" />"
L "`t</styles>"
L ''
L "`t<!--"
L "`t`tGeneric, server-driven slots. custom_hud_layout labels only take plain text, so every piece of"
L "`t`ttext is its own label. The plugin sets each label's text (dialog variable named like its id) and"
L "`t`ttoggles the classes documented in surftimer_hud.css, so content and styling change without"
L "`t`trepublishing this addon. Ids and sizes must match the SurfTimer plugin's src/ST-Player/CustomHud.cs."
L "`t`tGenerated by tools/generate_layout.ps1 - regenerate instead of editing by hand."
L "`t-->"
L "`t<Panel class=`"SurfTimerHud`" hittest=`"false`">"

GridSlot 'top' 'SlotTop' 4 8

# Center: rows of fields (label + value segments)
L "`t`t<Panel id=`"st_center`" class=`"Slot SlotCenter hidden`" hittest=`"false`">"
for ($r = 0; $r -lt 2; $r++) {
	L "`t`t`t<Panel id=`"st_fields_$r`" class=`"Fields hidden`" hittest=`"false`">"
	for ($f = 0; $f -lt 4; $f++) {
		$fid = "st_field_${r}_$f"
		L "`t`t`t`t<Panel id=`"$fid`" class=`"Field hidden`" hittest=`"false`">"
		Seg "`t`t`t`t`t" "${fid}_lbl" "Seg lbl FieldLabel"
		L "`t`t`t`t`t<Panel id=`"${fid}_row`" class=`"FieldRow`" hittest=`"false`">"
		for ($s = 0; $s -lt 6; $s++) { Seg "`t`t`t`t`t`t" "${fid}_$s" "Seg val FieldVal hidden" }
		L "`t`t`t`t`t</Panel>"
		L "`t`t`t`t</Panel>"
	}
	L "`t`t`t</Panel>"
}
L "`t`t</Panel>"
L ""

GridSlot 'left' 'SlotLeft' 7 4
GridSlot 'right' 'SlotRight' 9 2

# Popup menu (last, so it's drawn over the HUD). Buttons report clicks to the server by their id
# (OnCustomHudClicked); the labels inside them don't take clicks themselves.
L "`t`t<Panel id=`"st_menu`" class=`"Menu hidden`">"
L "`t`t`t<Panel class=`"MenuHeader`" hittest=`"false`">"
L "`t`t`t`t<Button id=`"st_menu_back`" class=`"MenuBack hidden`">"
L "`t`t`t`t`t<Label class=`"MenuBackLabel`" hittest=`"false`" text=`"&lt;`" />"
L "`t`t`t`t</Button>"
L "`t`t`t`t<Label id=`"st_menu_title`" class=`"MenuTitle`" hittest=`"false`" text=`"{s:st_menu_title}`" />"
L "`t`t`t`t<Button id=`"st_menu_close`" class=`"MenuClose`">"
L "`t`t`t`t`t<Label class=`"MenuCloseLabel`" hittest=`"false`" text=`"X`" />"
L "`t`t`t`t</Button>"
L "`t`t`t</Panel>"
L "`t`t`t<Label id=`"st_menu_status`" class=`"MenuStatus hidden`" hittest=`"false`" text=`"{s:st_menu_status}`" />"
L "`t`t`t<Panel id=`"st_menu_tabs`" class=`"MenuTabs hidden`" hittest=`"false`">"
for ($t = 0; $t -lt $MenuTabs; $t++) {
	L "`t`t`t`t<Button id=`"st_menu_tab_$t`" class=`"MenuTab hidden`">"
	L "`t`t`t`t`t<Label id=`"st_menu_tab_${t}_lbl`" class=`"MenuTabLabel`" hittest=`"false`" text=`"{s:st_menu_tab_${t}_lbl}`" />"
	L "`t`t`t`t</Button>"
}
L "`t`t`t</Panel>"
for ($i = 0; $i -lt $MenuItems; $i++) {
	$iid = "st_menu_item_$i"
	L "`t`t`t<Button id=`"$iid`" class=`"MenuItem hidden`">"
	L "`t`t`t`t<Label id=`"${iid}_num`" class=`"MenuNum`" hittest=`"false`" text=`"{s:${iid}_num}`" />"
	L "`t`t`t`t<Label id=`"${iid}_text`" class=`"MenuText`" hittest=`"false`" text=`"{s:${iid}_text}`" />"
	L "`t`t`t`t<Label id=`"${iid}_sub`" class=`"MenuSub`" hittest=`"false`" text=`"{s:${iid}_sub}`" />"
	L "`t`t`t`t<Label id=`"${iid}_right`" class=`"MenuRight`" hittest=`"false`" text=`"{s:${iid}_right}`" />"
	L "`t`t`t</Button>"
}
L "`t`t`t<Panel class=`"MenuFooter`" hittest=`"false`">"
L "`t`t`t`t<Button id=`"st_menu_prev`" class=`"MenuPage`">"
L "`t`t`t`t`t<Label class=`"MenuPageButtonLabel`" hittest=`"false`" text=`"&lt; Prev`" />"
L "`t`t`t`t</Button>"
L "`t`t`t`t<Label id=`"st_menu_page`" class=`"MenuPageLabel`" hittest=`"false`" text=`"{s:st_menu_page}`" />"
L "`t`t`t`t<Button id=`"st_menu_next`" class=`"MenuPage`">"
L "`t`t`t`t`t<Label class=`"MenuPageButtonLabel`" hittest=`"false`" text=`"Next &gt;`" />"
L "`t`t`t`t</Button>"
L "`t`t`t</Panel>"
L "`t`t</Panel>"

L "`t</Panel>"
L '</root>'

[System.IO.File]::WriteAllText($Out, $sb.ToString().Replace("`r`n", "`n"), [System.Text.UTF8Encoding]::new($false))
